# Numpy Basics

One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on large arrays of data.

In [13]:
import numpy as np

In [14]:
# Numpy
n_iter = 1_000_000
%timeit np.arange(n_iter) ** 2

2.15 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [19]:
%timeit list((n**2 for n in range(n_iter)))

241 ms ± 3.02 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
%timeit [n**2 for n in range(n_iter)]

233 ms ± 7.94 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### `ndarray`: A Multidimensional Array Object

In [23]:
# Simple math operations
math_test = np.array(([1.5, 0.2, -1.2], [2.7, -1.9, -1.1]))

print(math_test * 7)  # all values got multiplied by a scalar
print(math_test + math_test)  # corresponding cell gets added to itself

[[ 10.5   1.4  -8.4]
 [ 18.9 -13.3  -7.7]]
[[ 3.   0.4 -2.4]
 [ 5.4 -3.8 -2.2]]


All `ndarrays` have these structural properties:

* Dimension: Number of indices
* Shape: Size of the array in each direction
* Size: Total number of elements in an array

In [31]:
print(f"Dimension: {math_test.ndim}", f"Shape: {math_test.shape}", f"Size: {math_test.size}", sep="\n")

Dimension: 2
Shape: (2, 3)
Size: 6


In [27]:
math_test.dtype

dtype('float64')

### Creating Arrays

In [35]:
data1 = [1, 2, 3.2, 8, 7]
arr1 = np.array(data1)
arr1

array([1. , 2. , 3.2, 8. , 7. ])

In [36]:
data2 = [[1, 9, 3, 5], [3, 5, 2, 8]]
arr2 = np.array(data2)
arr2

array([[1, 9, 3, 5],
       [3, 5, 2, 8]])

In [45]:
[f"arr{i+1}: {d_type}" for i, d_type in enumerate([arr.dtype for arr in [arr1, arr2]])]

['arr1: float64', 'arr2: int64']

Unless explicitly specified, `np.array` will try to infer the dtype for the array that was created.

In [55]:
# Array for given length or shape:
print(np.zeros(5))
print(np.zeros((2, 3)))
print(np.ones((2, 4, 3)))
print(np.empty(5)) # not safe: can contain non-zero values

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[0. 0. 0. 0. 0.]


In [59]:
np.arange(1, 10, 2) # Similar to the range function

array([1, 3, 5, 7, 9])

In [72]:
np.identity(5)
#OR
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Data Types 