# Numpy Basics

One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on large arrays of data.

In [13]:
import numpy as np

In [14]:
# Numpy
n_iter = 1_000_000
%timeit np.arange(n_iter) ** 2

2.15 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [19]:
%timeit list((n**2 for n in range(n_iter)))

241 ms ± 3.02 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
%timeit [n**2 for n in range(n_iter)]

233 ms ± 7.94 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### `ndarray`: A Multidimensional Array Object

In [23]:
# Simple math operations
math_test = np.array(([1.5, 0.2, -1.2], [2.7, -1.9, -1.1]))

print(math_test * 7)  # all values got multiplied by a scalar
print(math_test + math_test)  # corresponding cell gets added to itself

[[ 10.5   1.4  -8.4]
 [ 18.9 -13.3  -7.7]]
[[ 3.   0.4 -2.4]
 [ 5.4 -3.8 -2.2]]


All `ndarrays` have these structural properties:

* Dimension: Number of indices
* Shape: Size of the array in each direction
* Size: Total number of elements in an array

In [24]:
math_test.shape

(2, 3)